# Generated by Django 3.2.6 on 2021-12-04 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Fine_amount', models.IntegerField(default=0, max_length=50)),
                ('When', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='demo',
            name='Date_Time',
            field=models.CharField(default=datetime.date(2021, 12, 4), max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 12, 4)),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 12, 4)),
        ),
    ]
