# Generated by Django 3.2.6 on 2021-12-11 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0003_auto_20211207_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='castomuser',
            name='Tolal_Due',
            field=models.IntegerField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='all_meal_order',
            name='When',
            field=models.CharField(default='Breakfast', max_length=30),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Date_Time',
            field=models.CharField(default=datetime.date(2021, 12, 11), max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
    ]
