# Generated by Django 3.2.6 on 2022-02-02 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0006_auto_20211211_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='Date_Time',
            field=models.CharField(default=datetime.date(2022, 2, 2), max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 2)),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 2)),
        ),
    ]
